# Generated by cpp11: do not edit by hand

cpp_pip <- function(layer, xy) {
  .Call(`_utaengine_cpp_pip`, layer, xy)
}

cpp_index_sort <- function(index0) {
  .Call(`_utaengine_cpp_index_sort`, index0)
}
