# Generated by cpp11: do not edit by hand

cpp_pip <- function (layer, xy) {
    .Call (`_uaengine_cpp_pip`, layer, xy)
}

cpp_index_sort <- function (index0) {
    .Call (`_uaengine_cpp_index_sort`, index0)
}
