# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_dists_to_n_targets
#'
#' @noRd
rcpp_dists_to_n_targets <- function(graph, vert_map_in, fromi, toi_in, n_targets) {
    .Call(`_utaengine_rcpp_dists_to_n_targets`, graph, vert_map_in, fromi, toi_in, n_targets)
}

